[package]
name = "ice-server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
surrealdb = "2.1.4"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
